/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ViewRouteImport } from './routes/view'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ViewItemIdRouteImport } from './routes/view.$itemId'
import { Route as AdminVerifiedRouteImport } from './routes/admin.verified'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as AdminSigninRouteImport } from './routes/admin.signin'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPendingRouteImport } from './routes/admin.pending'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ViewItemIdRoute = ViewItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ViewRoute,
} as any)
const AdminVerifiedRoute = AdminVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSigninRoute = AdminSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/upload': typeof UploadRoute
  '/view': typeof ViewRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/view/$itemId': typeof ViewItemIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/view': typeof ViewRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/view/$itemId': typeof ViewItemIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/upload': typeof UploadRoute
  '/view': typeof ViewRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/view/$itemId': typeof ViewItemIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/upload'
    | '/view'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/data'
    | '/admin/pending'
    | '/admin/settings'
    | '/admin/signin'
    | '/admin/signup'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verified'
    | '/view/$itemId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/view'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/data'
    | '/admin/pending'
    | '/admin/settings'
    | '/admin/signin'
    | '/admin/signup'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verified'
    | '/view/$itemId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/upload'
    | '/view'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/data'
    | '/admin/pending'
    | '/admin/settings'
    | '/admin/signin'
    | '/admin/signup'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verified'
    | '/view/$itemId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UploadRoute: typeof UploadRoute
  ViewRoute: typeof ViewRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/view/$itemId': {
      id: '/view/$itemId'
      path: '/$itemId'
      fullPath: '/view/$itemId'
      preLoaderRoute: typeof ViewItemIdRouteImport
      parentRoute: typeof ViewRoute
    }
    '/admin/verified': {
      id: '/admin/verified'
      path: '/verified'
      fullPath: '/admin/verified'
      preLoaderRoute: typeof AdminVerifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signin': {
      id: '/admin/signin'
      path: '/signin'
      fullPath: '/admin/signin'
      preLoaderRoute: typeof AdminSigninRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSigninRoute: typeof AdminSigninRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifiedRoute: typeof AdminVerifiedRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSigninRoute: AdminSigninRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifiedRoute: AdminVerifiedRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ViewRouteChildren {
  ViewItemIdRoute: typeof ViewItemIdRoute
}

const ViewRouteChildren: ViewRouteChildren = {
  ViewItemIdRoute: ViewItemIdRoute,
}

const ViewRouteWithChildren = ViewRoute._addFileChildren(ViewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UploadRoute: UploadRoute,
  ViewRoute: ViewRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
